#! /bin/sh

date > all.log

for i in *.t
do
  ./$i >> all.log 2>&1
done

date >> all.log

START=`head -1 all.log`
END=`tail -1 all.log`
OS=`uname`

case $OS in
  Darwin | FreeBSD)
    STARTEPOCH=`date -j -f "%a %b %d %T %Z %Y" "${START}" "+%s"`
    ENDEPOCH=`date -j -f "%a %b %d %T %Z %Y" "${END}" "+%s"`
    ;;
  Linux)
    STARTEPOCH=`date "+%s" -d "${START}"`
    ENDEPOCH=`date "+%s" -d "${END}"`
    ;;
esac

RUNTIME=$(($ENDEPOCH - $STARTEPOCH))

echo -n 'Pass: '
grep ^ok all.log | wc -l
echo -n 'Fail: '
grep ^not all.log | wc -l
echo -n 'Runtime:   '
echo $RUNTIME
