#!/bin/sh

printf "C++:     %5d\n" $(ls *.test.cpp | wc -l)
printf "Python:  %5d\n" $(head -n1 *.test.py | grep -a '\bpython' | wc -l)
printf "Bash:    %5d\n" $(head -n1 *.test.sh | grep -a '\bbash' | wc -l)
echo
printf "Feature  %5d\n" $(ls feature.*.test.py | wc -l)
printf "Bug      %5d\n" $(ls tw-*.test.sh | wc -l)
echo
printf "Total:   %5d\n" $(ls *.test.* | wc -l)
