#!/bin/bash

mkdir -p local/bin
mkdir -p local/share/doc/task/scripts/bash
mkdir -p local/share/doc/task/scripts/vim/ftdetect
mkdir -p local/share/doc/task/scripts/vim/syntax
mkdir -p local/share/doc/task/scripts/zsh
mkdir -p local/share/doc/task/scripts/fish
mkdir -p local/share/doc/task/rc
mkdir -p local/share/man/man1
mkdir -p local/share/man/man5

cp ../../README                 README.txt
cp ../../COPYING                COPYING.txt

cp ../../src/task               local/bin/

cp ../../AUTHORS                local/share/doc/task/
cp ../../ChangeLog              local/share/doc/task/
cp ../../COPYING                local/share/doc/task/
cp ../../NEWS                   local/share/doc/task/
cp ../../README                 local/share/doc/task/

cp ../../scripts/bash/*         local/share/doc/task/scripts/bash
cp ../../scripts/vim/README     local/share/doc/task/scripts/vim
cp ../../scripts/vim/ftdetect/* local/share/doc/task/scripts/vim/ftdetect
cp ../../scripts/vim/syntax/*   local/share/doc/task/scripts/vim/syntax
cp ../../scripts/zsh/*          local/share/doc/task/scripts/zsh
cp ../../scripts/fish/*         local/share/doc/task/scripts/fish

cp ../../doc/rc/*.theme         local/share/doc/task/rc
cp ../../doc/rc/holidays*       local/share/doc/task/rc

cp ../../doc/man/*.1            local/share/man/man1
cp ../../doc/man/*.5            local/share/man/man5

