sudo: required
language: generic
matrix:
  include:
    - name: "Fedora 28"
      os: linux
      env: CONTAINER=fedora28
      services: docker
    - name: "Debian Stable"
      os: linux
      env: CONTAINER=debianstable
      services: docker
    - name: "Ubuntu 16.04"
      os: linux
      env: CONTAINER=ubuntu1604
      services: docker
    - name: "Ubuntu 18.04"
      os: linux
      env: CONTAINER=ubuntu1804
      services: docker
    - name: "Mac OS X"
      os: osx
      env: CONTAINER=osx
install:
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - if [[ $CONTAINER != "osx" ]]; then docker-compose build test-$CONTAINER || travis_terminate 1; fi
script:
  - if [[ $CONTAINER != "osx" ]]; then docker-compose up test-$CONTAINER || travis_terminate 1; else bash test/scripts/test_osx.sh || travis_terminate 1 ; fi
