[workspace]

members = [
    "taskchampion/taskchampion",
    "taskchampion/sync-server",
    "taskchampion/lib",
    "taskchampion/integration-tests",
    "taskchampion/xtask",
]

# src/tc/rust is just part of the TW build and not a public crate
exclude = [ "src/tc/rust" ]
