.TH task-tutorial 5 2009-05-30 "Task 1.8.0" "User Manuals"

.SH NAME
task-tutorial \- A tutorial for the task(1) command line todo manager.

.SH DESCRIPTION
Task is a command line TODO list manager. It maintains a list of tasks that you
want to do, allowing you to add/remove, and otherwise manipulate them.  Task
has a rich list of subcommands that allow you to do various things with it.

.SH 30 second tutorial
30 second tutorial

.SH Simple usage of task
Simple usage of task

.SH Advanced usage of task
Advanced usage of task

.SH "CREDITS & COPYRIGHTS"
task was written by P. Beckingham <task@beckingham.net>.
.br
Copyright (C) 2006 \- 2009 P. Beckingham

This man page was originally written by Federico Hernandez. It is based on the task man page, which
was originally written by P.C. Shyamshankar.

task is distributed under the GNU General Public License.  See
http://www.gnu.org/licenses/gpl-2.0.txt for more information.

.SH SEE ALSO
.BR task(1),
.BR taskrc(5)

For more information regarding task, the following may be referenced:

.TP
The official site at
<http://taskwarrior.org>

.TP
The official code repository at
<http://github.com/pbeckingham/task/>

.SH REPORTING BUGS
.TP
Bugs in task may be reported to the issue-tracker at
<http://taskwarrior.org>
