[package]
name = "xtask"
version = "0.4.1" 
edition = "2018"
# rust-version = "1.65" # Used for testing xtask MSRV functionality

[dependencies]
anyhow.workspace = true

taskchampion-lib = { path = "../lib" }

regex = "^1.9.4"
