.TH task-faq 5 2010-01-03 "task 1.9.0" "User Manuals"

.SH NAME
task-faq \- A FAQ for the task(1) command line todo manager.

.SH DESCRIPTION
Task is a command line TODO list manager. It maintains a list of tasks that you
want to do, allowing you to add/remove, and otherwise manipulate them.  Task
has a rich list of commands that allow you to do various things with it.

.SH WELCOME
Welcome to the task FAQ.  If you have would like to see a question answered
here, please send us a note at <support@taskwarrior.org>.

.TP
.B Q: Where does task store the data?
By default, task creates a .taskrc file in your home directory and populates it
with defaults.  Task also creates a .task directory in your home directory and
puts data files there.

.TP
.B Q: Can I edit that data?
Of course you can.  It is a simple text file, and looks somewhat like the JSON
format, and if you are careful not to break the format, there is no reason not
to edit it.  But task provides a rich command set to do that manipulation for
you, so it is probably best to leave those files alone.

.TP
.B Q: How do I restore my .taskrc file to defaults?
If you delete (or rename) your .taskrc file, task will offer to create a default
one for you.  Another way to do this is with the command:

    $ task rc:new-file version

Task will create 'new-file' if it doesn't already exist.  Note that this is a
good way to learn about new configuration settings, if your .taskrc file was
created by an older version of task.

.TP
.B Q: Do I need to back up my task data?
Yes.  You should back up your ~/.task directory, and probably your ~/.taskrc
file too.

.TP
.B Q: Can I share my tasks between different machines?

.TP
.B Q: The undo.data file gets very large - do I need it?
You need it if you want the undo capability.  But if it gets large, you can
certainly truncate it to save space, just be careful to delete lines from the
top of the file, up to and including a separator '---'.  Note that it does not
slow down task, because task never reads it until you want to undo.  Otherwise
task only appends to the file.

.TP
.B Q: How do I know whether my terminal support 256 colors?
You will need to make sure your TERM environment variable is set to xterm-color,
otherwise the easiest way is to just try it!  With task 1.9 or later, you simply
run

    $ task color

and a full color palette is displayed.  If you see only 8 or 16 colors, perhaps
with those colors repeated, then your terminal does not support 256 colors.

We have had success with xterm, and iTerm for the Mac.

.TP
.B Q: How do I make use of all these colors?
See the task-color(5) man page for an in-depth explanation of the task color
rules.

.TP
.B Q: How can I make task put the command in the terminal window title?
You cannot.  But you can make the shell do it, and you can make the shell
call the task program.  Here is a Bash script that does this:

    #! /bin/bash

    printf "\033]0;task $*\a"
    /usr/local/bin/task $*

You just need to run the script, and let the script run task.  Here is a Bash
function that does the same thing:

    t ()
    {
      printf "\033]0;task $*\a"
      /usr/local/bin/task $*
    }

.SH "CREDITS & COPYRIGHTS"
task was written by P. Beckingham <paul@beckingham.net>.
.br
Copyright (C) 2006 \- 2010 P. Beckingham

This man page was originally written by P. Beckingham.

task is distributed under the GNU General Public License.  See
http://www.gnu.org/licenses/gpl-2.0.txt for more information.

.SH SEE ALSO
.BR task(1),
.BR taskrc(5),
.BR task-tutorial(5)
.BR task-color(5)

For more information regarding task, the following may be referenced:

.TP
The official site at
<http://taskwarrior.org>

.TP
The official code repository at
<git://tasktools.org/task.git/>

.TP
You can contact the project by writing an email to
<support@taskwarrior.org>

.SH REPORTING BUGS
.TP
Bugs in task may be reported to the issue-tracker at
<http://taskwarrior.org>
