.TH task-faq 5 2010-01-03 "task 1.9.0" "User Manuals"

.SH NAME
task-faq \- A FAQ for the task(1) command line todo manager.

.SH DESCRIPTION
Task is a command line TODO list manager. It maintains a list of tasks that you
want to do, allowing you to add/remove, and otherwise manipulate them.  Task
has a rich list of commands that allow you to do various things with it.

.SH WELCOME
Welcome to the task FAQ.  If you have would like to see a question answered
here, please send us a note at <support@taskwarrior.org>.

.TP
.B Q: Where does task store the data?
By default, task creates a .taskrc file in your home directory and populates it
with defaults.  Task also creates a .task directory in your home directory and
puts data files there.

.TP
.B Q: Can I edit that data?
Of course you can.  It is a simple text file, and looks somewhat like the JSON
format, and if you are careful not to break the format, there is no reason not
to edit it.  But task provides a rich command set to do that manipulation for
you, so it is probably best to leave those files alone.

.TP
.B Q: How do I restore my .taskrc file to defaults?
If you delete (or rename) your .taskrc file, task will offer to create a default
one for you.  Another way to do this is with the command:

    $ task rc:new-file version

Task will create 'new-file' if it doesn't already exist.  Note that this is a
good way to learn about new configuration settings, if your .taskrc file was
created by an older version of task.

.TP
.B Q: Can I share my tasks between different machines?

.TP
.B Q: The undo.data file gets very large - do I need it?

.TP
.B Q: How do I know whether my terminal support 256 colors?

.SH "CREDITS & COPYRIGHTS"
task was written by P. Beckingham <paul@beckingham.net>.
.br
Copyright (C) 2006 \- 2010 P. Beckingham

This man page was originally written by P. Beckingham.

task is distributed under the GNU General Public License.  See
http://www.gnu.org/licenses/gpl-2.0.txt for more information.

.SH SEE ALSO
.BR task(1),
.BR taskrc(5),
.BR task-tutorial(5)

For more information regarding task, the following may be referenced:

.TP
The official site at
<http://taskwarrior.org>

.TP
The official code repository at
<git://tasktools.org/task.git/>

.TP
You can contact the project by writing an email to
<support@taskwarrior.org>

.SH REPORTING BUGS
.TP
Bugs in task may be reported to the issue-tracker at
<http://taskwarrior.org>
