[package]
name = "tc-rust"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
taskchampion = { path = "../../../taskchampion/taskchampion", features = ["server-gcp", "server-sync"] }
taskchampion-lib = { path = "../../../taskchampion/lib" }
