FROM ubuntu:latest

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get --yes install tzdata && \
    apt-get install --yes build-essential cmake git uuid-dev libgnutls28-dev libfaketime && \
    apt-get install --yes python

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

CMD ["/bin/bash"]
