# GNU Readline library finder
if (READLINE_INCLUDE_DIR AND READLINE_LIBRARIES)
  set (READLINE_FOUND TRUE)
else (READLINE_INCLUDE_DIR AND READLINE_LIBRARIES)
  find_path (READLINE_INCLUDE_DIR readline/readline.h)
  find_library (READLINE_LIBRARIES readline)
  mark_as_advanced (READLINE_INCLUDE_DIR READLINE_LIBRARIES)
endif (READLINE_INCLUDE_DIR AND READLINE_LIBRARIES)
