name: docs

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  mdbook-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          # if this changes, change it in .github/workflows/checks.yml as well
          mdbook-version: '0.4.10'

      - run: mdbook build taskchampion/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./taskchampion/docs/book
          destination_dir: taskchampion
