#!/bin/bash

# The on-add event is triggered separately for each task added

# Input:
# - A line of JSON for the task added
read new_task

# Processing goes here

# Output:
# - all emitted JSON lines must be fully-formed tasks
# - all emitted non-JSON lines are considered feedback messages
echo on-add

# Exit:
#   0 Means: - all emitted JSON lines are added/modified
#            - all emitted non-JSON lines become footnote entries
#   1 Means: - all emitted JSON lines are ignored
#            - all emitted non-JSON lines become error entries
exit 0

