#!/bin/bash

# The on-add event is triggered separately for each task added

# Input:
# - line of JSON for the task added

# Output:
# - all emitted JSON lines are added/modified as tasks, if the exit code is
#   zero, otherwise ignored.
# - minimal new task:  {"description":"Buy milk"}
# - to modify a task include complete JSON
# - all emitted non-JSON lines are considered feedback messages if the exit
#   code is zero, otherwise they are considerederrors.

read new_task

echo $new_task
echo 'on-add'
exit 0
