#!/bin/bash

# The on-exit event is triggered once, after all processing is complete

# Input:
# - A read-only line of JSON for each task added/modified

# Processing goes here

# Output:
# - all emitted non-JSON lines are considered feedback messages
echo on-exit

# Exit:
#   0 Means:     - all emitted non-JSON lines become footnote entries
#   non-0 Means: - all emitted non-JSON lines become error entries
exit 0

