#!/bin/sh

# The on-launch event is triggered once, after initialization, before any
# processing occurs. This hooks script has no effect on processing.

# Input:
# - None

# Output:
# - Optional feedback/error.
echo 'on-launch'

# Status:
# - 0:     JSON ignored, non-JSON is feedback.
# - non-0: JSON ignored, non-JSON is error.
exit 0

