#!/bin/bash

# The on-launch event is triggered once, after initialization, before any
# processing occurs, i.e first

# Input:
# - none

# Output:
# - all emitted JSON lines are added/modified as tasks, if the exit code is
#   zero, otherwise ignored.
# - minimal new task:  {"description":"Buy milk"}
# - to modify a task include complete JSON
# - all emitted non-JSON lines are considered feedback messages if the exit
#   code is zero, otherwise they are considered errors.

echo 'on-launch'
exit 0
