#!/bin/bash

# The on-launch event is triggered once, after initialization, before an
# processing occurs

# No input

# Processing goes here

# Output:
# - all emitted JSON lines must be fully-formed tasks
# - all emitted non-JSON lines are considered feedback messages
echo on-launch

# Exit:
#   0 Means: - all emitted JSON lines are added/modified
#            - all emitted non-JSON lines become footnote entries
#   1 Means: - all emitted JSON lines are ignored
#            - all emitted non-JSON lines become error entries
exit 0

