#!/bin/bash

# The on-modify event is triggered separately for each task added or modified

# Input:
# - A line of JSON for the original task
# - A line of JSON for the modified task
read original_task
read modified_task

# Processing goes here

# Output:
# - all emitted JSON lines must be fully-formed tasks
# - all emitted non-JSON lines are considered feedback messages
echo on-modify

# Exit:
#   0 Means:     - all emitted JSON lines are added/modified
#                - all emitted non-JSON lines become footnote entries
#   non-0 Means: - all emitted JSON lines are ignored
#                - all emitted non-JSON lines become error entries
exit 0

